import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import project.*;
import java.time.LocalDate;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DELL
 */
public class List_of_products extends javax.swing.JFrame {
    private int check;
    /**
     * Creates new form List_of_products
     */
    private static int order_id;
    private static int total_p;

    public static int getTotal_price() {
        return total_p;
    }

    public static void setTotal_price(int total_price) {
        List_of_products.total_p = total_price;
    }

    public int getOrder_id() {
        return order_id;
    }

    public static void setOrder_id(int order_id) {
        List_of_products.order_id = order_id;
    }
    
    public List_of_products() {
        initComponents();
        check = 0;
        Login login = new Login();
        try{
            if(login.getAdmin()>0){
                btnCart.setVisible(false);
                lblQuantity.setVisible(false);
                txtQuantity.setVisible(false);
                btnOrderList.setVisible(false);
            }
            else{
                btnCart.setVisible(true);
                lblQuantity.setVisible(true);
                txtQuantity.setVisible(true);
                btnOrderList.setVisible(true);
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        btnCart = new javax.swing.JButton();
        lblQuantity = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        btnOrderList = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(0, 118, 221));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Id", "Product name", "Price", "Quantity", "Catagories"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 156, 671, -1));

        jLabel1.setFont(new java.awt.Font("Bodoni MT Condensed", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 118, 221));
        jLabel1.setText("List of Products");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(745, 13, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 36, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 118, 221));
        jLabel2.setText("Filter");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 220, -1, -1));

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(0, 118, 221));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Electronics", "Cosmetics", "Gaming", "Fashion", "Cookware" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 277, 229, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 118, 221));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search.png"))); // NOI18N
        jButton2.setText("FIND");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 328, -1, -1));

        btnCart.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCart.setForeground(new java.awt.Color(0, 118, 221));
        btnCart.setText("Add to cart");
        btnCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCartActionPerformed(evt);
            }
        });
        jPanel1.add(btnCart, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, -1));

        lblQuantity.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblQuantity.setForeground(new java.awt.Color(0, 118, 221));
        lblQuantity.setText("Total Quantity");
        jPanel1.add(lblQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 449, -1, -1));

        txtQuantity.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtQuantity.setForeground(new java.awt.Color(0, 118, 221));
        jPanel1.add(txtQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 446, 81, -1));

        btnOrderList.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnOrderList.setForeground(new java.awt.Color(0, 118, 221));
        btnOrderList.setText("Order List");
        btnOrderList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderListActionPerformed(evt);
            }
        });
        jPanel1.add(btnOrderList, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/listp.jpg"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 610));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Login login = new Login();
        if(login.getAdmin() > 0){
            setVisible(false);
        }
        else{
            setVisible(false);
            new Login().setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        try{
            Connection con = ConnectionOracle.getCon();
            Statement st = con.createStatement();
            if((String)jComboBox1.getSelectedItem() == "All"){
                ResultSet rs = st.executeQuery("Select * from product");
                if(check==1){
                       model.setRowCount(0);
                }
                while(rs.next()){
                    model.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5)});
                    
                }
                check=1;
            }
            else if((String)jComboBox1.getSelectedItem() == "Electronics"){
                ResultSet vs = st.executeQuery("SELECT * FROM product WHERE categories LIKE 'Electronics'");
                if(check==1){
                    model.setRowCount(0);
                }
                while(vs.next()){
                    model.addRow(new Object[]{vs.getString(1),vs.getString(2),vs.getString(3),vs.getString(4),vs.getString(5)});
                }
                check=1;
            }
            else if((String)jComboBox1.getSelectedItem() == "Cosmetics"){
                ResultSet vs = st.executeQuery("SELECT * FROM product WHERE categories LIKE 'Cosmetics'");
                if(check==1){
                    model.setRowCount(0);
                }
                while(vs.next()){
                    model.addRow(new Object[]{vs.getString(1),vs.getString(2),vs.getString(3),vs.getString(4),vs.getString(5)});
                }
                check=1;
            }
            else if((String)jComboBox1.getSelectedItem() == "Gaming"){
                ResultSet vs = st.executeQuery("SELECT * FROM product WHERE categories LIKE 'Gaming'");
                if(check==1){
                    model.setRowCount(0);
                }
                
                while(vs.next()){
                    model.addRow(new Object[]{vs.getString(1),vs.getString(2),vs.getString(3),vs.getString(4),vs.getString(5)});
                }
                check=1;
            }
            else if((String)jComboBox1.getSelectedItem() == "Fashion"){
                ResultSet vs = st.executeQuery("SELECT * FROM product WHERE categories LIKE 'Fashion'");
                if(check==1){
                    model.setRowCount(0);
                }
                while(vs.next()){
                    model.addRow(new Object[]{vs.getString(1),vs.getString(2),vs.getString(3),vs.getString(4),vs.getString(5)});
                }
                check=1;
            }
            else if((String)jComboBox1.getSelectedItem() == "Cookware"){
                ResultSet vs = st.executeQuery("SELECT * FROM product WHERE categories LIKE 'Cookware'");
                if(check==1){
                    model.setRowCount(0);
                }
                while(vs.next()){
                    
                    model.addRow(new Object[]{vs.getString(1),vs.getString(2),vs.getString(3),vs.getString(4),vs.getString(5)});
                }
                check=1;
            }
            else{
                JOptionPane.showMessageDialog(null, "Product not found");
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCartActionPerformed
        
        try {
            Login user = new Login();
            int[] selectedRow = jTable1.getSelectedRows();
            Connection con = ConnectionOracle.getCon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT max(order_id) FROM order_table");
            int id = 0;
            if (rs.next()) {
                id = rs.getInt(1) + 1; 
            } else {
                id = 1;
            }

            LocalDate currentDate = LocalDate.now();
            int quantity = Integer.parseInt(txtQuantity.getText());
            int u_id = user.getUser(); 
            if(quantity == 0){
                JOptionPane.showMessageDialog(null, "Please enter quantity");
            }
            else{
                for (int i = 0; i < selectedRow.length; i++) {
                    int row = selectedRow[i];
                    String column1Data = jTable1.getValueAt(row, 0).toString();
                    String column2Data = jTable1.getValueAt(row, 2).toString();
                    String column3Data = jTable1.getValueAt(row, 3).toString();
                    int p_id = Integer.parseInt(column1Data);
                    int price = Integer.parseInt(column2Data);
                    int quantity2 = Integer.parseInt(column3Data);
                    int total_price = price * quantity;
                    setTotal_price(total_price);
                    int quantity1 = quantity2 - quantity;

                    PreparedStatement ps = con.prepareStatement("INSERT INTO order_table VALUES (?, ?, ?, ?, ?)");
                    ps.setInt(1, id);
                    ps.setDate(2, Date.valueOf(currentDate));
                    ps.setInt(3, quantity);
                    ps.setInt(4, p_id);
                    ps.setInt(5, u_id);
                    ps.executeUpdate();

                    PreparedStatement ps1 = con.prepareStatement("UPDATE product SET quantity = ? WHERE p_id = ?");
                    ps1.setInt(1, quantity1);
                    ps1.setInt(2, p_id);
                    ps1.executeUpdate();

                    JOptionPane.showMessageDialog(null, "Product is added to cart");
                    setOrder_id(id);
                    setVisible(false);
                    new Payment().setVisible(true);
                }
                rs.close();
                st.close();
                con.close();
                
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }


    }//GEN-LAST:event_btnCartActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void btnOrderListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderListActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new List_of_orders().setVisible(true);
    }//GEN-LAST:event_btnOrderListActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(List_of_products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(List_of_products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(List_of_products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(List_of_products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new List_of_products().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCart;
    private javax.swing.JButton btnOrderList;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblQuantity;
    private javax.swing.JTextField txtQuantity;
    // End of variables declaration//GEN-END:variables
}
