import java.sql.*;
import javax.swing.JOptionPane;
import org.hsqldb.TypeInvariants;
import project.ConnectionOracle;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DELL
 */
public class Payment extends javax.swing.JFrame {

    /**
     * Creates new form Payment
     */
    List_of_products order = new List_of_products();
    public Payment() {
        initComponents();
        try{
            int id=1;
            String u_name = "";
            String u_id = "";
            String p_name = "";
            String p_id = "";
            int total_price = order.getTotal_price();
            String method = txtmethod.getText();
            String str = String.valueOf(id);
            txtId.setText(str);
            Connection con = ConnectionOracle.getCon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select max(payment_id) from payment");
            if(rs.next()){
                id = rs.getInt(id) + 1;
                txtId.setText(""+id);
            }

              PreparedStatement ps = con.prepareStatement("SELECT u.user_name,u.user_id, p.p_name, p.p_id FROM user_table u JOIN order_table o ON (u.user_id = o.user_id) JOIN product p ON (o.p_id = p.p_id) WHERE o.order_id = ?");
              ps.setString(1, String.valueOf(order.getOrder_id()));
              rs = ps.executeQuery();
              if(rs.next()){
                  u_name = rs.getString("user_name");
                  u_id = rs.getString("user_id");
                  p_name = rs.getString("p_name");
                  p_id = rs.getString("p_id");
                  txtName.setText(u_name);
                  lblId.setText(u_id);
                  txtProduct.setText(p_name);
                  lblProduct.setText(p_id);
                  txtPrice.setText(String.valueOf(total_price));
              }
              
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtId = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtName = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtProduct = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtmethod = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblProduct = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Algerian", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 118, 221));
        jLabel1.setText("Payment");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 250, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 118, 221));
        jLabel2.setText("ID Number");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 103, -1, -1));

        txtId.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtId.setForeground(new java.awt.Color(0, 118, 221));
        txtId.setText("00");
        jPanel1.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 103, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 118, 221));
        jLabel4.setText("Name");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 267, -1, -1));

        txtName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtName.setForeground(new java.awt.Color(0, 118, 221));
        txtName.setText("User Name");
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 267, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 118, 221));
        jLabel6.setText("Product name");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 431, -1, -1));

        txtProduct.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtProduct.setForeground(new java.awt.Color(0, 118, 221));
        txtProduct.setText("Name");
        jPanel1.add(txtProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 431, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 118, 221));
        jLabel8.setText("Total price");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 513, -1, -1));

        txtPrice.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtPrice.setForeground(new java.awt.Color(0, 118, 221));
        txtPrice.setText("Price");
        jPanel1.add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 513, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 118, 221));
        jLabel10.setText("Payment method");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 595, -1, -1));

        txtmethod.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtmethod.setForeground(new java.awt.Color(0, 118, 221));
        txtmethod.setText("On Delivery");
        jPanel1.add(txtmethod, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 595, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 118, 221));
        jButton1.setText("Order Item");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 677, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 118, 221));
        jLabel3.setText("User Id");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 185, -1, -1));

        lblId.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblId.setForeground(new java.awt.Color(0, 118, 221));
        lblId.setText("User Id");
        jPanel1.add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 185, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 118, 221));
        jLabel7.setText("Product id");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 349, -1, -1));

        lblProduct.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblProduct.setForeground(new java.awt.Color(0, 118, 221));
        lblProduct.setText("Product id");
        jPanel1.add(lblProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 349, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/listp.jpg"))); // NOI18N
        jLabel5.setToolTipText("");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 730));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            Connection con = ConnectionOracle.getCon();
            String id = txtId.getText();
            String order_id = String.valueOf(order.getOrder_id());
            String total_price = String.valueOf(order.getTotal_price());
            String method = txtmethod.getText();
            PreparedStatement ps = con.prepareStatement("insert into payment values (?,?,?,?)");
            ps.setString(1, String.valueOf(id));
            ps.setString(2, String.valueOf(order_id));
            ps.setString(3, String.valueOf(total_price));
            ps.setString(4, method);
            ps.executeQuery();
            JOptionPane.showMessageDialog(null, "Your order has been placed");
            int a = JOptionPane.showConfirmDialog(null, "More Shopping :'-)","Select",JOptionPane.YES_NO_OPTION);
            if(a==0){
                setVisible(false);
                new List_of_products().setVisible(true);
            }
            else{
                JOptionPane.showMessageDialog(this, "Thanks for shopping");
                setVisible(false);
                new Login().setVisible(true);
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblProduct;
    private javax.swing.JLabel txtId;
    private javax.swing.JLabel txtName;
    private javax.swing.JLabel txtPrice;
    private javax.swing.JLabel txtProduct;
    private javax.swing.JLabel txtmethod;
    // End of variables declaration//GEN-END:variables
}
